# Generated by Django 6.0.2 on 2026-03-14 11:19

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=vendors.models.vendor_upload_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vendors.models.vendor_upload_path),
        ),
    ]
