# Generated by Django 6.0.2 on 2026-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
