# Generated by Django 6.0.2 on 2026-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authServices', '0003_remove_account_address_remove_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='bussiness_address',
            field=models.CharField(max_length=350),
        ),
    ]
