# Generated by Django 6.0.2 on 2026-02-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authServices', '0004_alter_vendorprofile_bussiness_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='bussiness_address',
            new_name='business_address',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
